// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBEG4_z1uLCyXBLzvaR7NLM5sl3RRBrEk',
    appId: '1:459218013502:web:2861174dc1828cd586706f',
    messagingSenderId: '459218013502',
    projectId: 'merhabaapp-5ed3c',
    authDomain: 'merhabaapp-5ed3c.firebaseapp.com',
    storageBucket: 'merhabaapp-5ed3c.firebasestorage.app',
    measurementId: 'G-H01N29Y1EP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM02Spt72Cnk0e1MI8ArfoMZI1szAPyJw',
    appId: '1:459218013502:android:9d23ea72c8a94f8486706f',
    messagingSenderId: '459218013502',
    projectId: 'merhabaapp-5ed3c',
    storageBucket: 'merhabaapp-5ed3c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpNC4K51sOlhqwJNnPcHgytAtXZT6B228',
    appId: '1:459218013502:ios:db7d81fe8d4d88c286706f',
    messagingSenderId: '459218013502',
    projectId: 'merhabaapp-5ed3c',
    storageBucket: 'merhabaapp-5ed3c.firebasestorage.app',
    iosBundleId: 'com.sherifshouaib.merhaba',
  );
}
